export const categories = [
  "All",
  "News",
  "Finance",
  "Budget",
  "Investment",
  "Loan",
  "GST",
  "Tax",
  "Saving",
  "Case Studies",
  "FinTech",
  "Calculator",
];

export const subcategoriesMap = {
  "Finance Blog": [
    "News",
    "Personal finance",
    "Behavioural finance",
    "Financial future planning",
    "Financial health (tips and measures)",
    "Financial challenges",
    "Financial advisor",
  ],
  "Budget": [
    "News",
    "Budget types",
    "Finance budget",
    "Static budget",
    "Production budget",
    "Budget elements",
  ],
  "Investment": [
    "News",
    "Investment strategies",
    "Investment plans",
    "Investment ideas",
    "Investment products",
    "Investment types",
    "Investment calculator",
    "Investment market",
  ],
  "Insurance": [
    "News",
    "Health insurance",
    "Some Life insurance",
    "Travel Insurance",
    "Car insurance",
    "Home Insurance",
    "Insurance advisor",
    "Insurance calculator",
  ],
  "Loan": [
    "News",
    "Home loan",
    "Personal loan",
    "Business loan",
    "Instant loan",
    "Vehicle loan",
    "Gold loan",
    "Secured loan",
  ],
  "GST": [
    "News",
    "GST collection",
    "GST calculator",
    "Types of GST",
    "CGST",
    "SGST",
    "UTGST",
    "IGST",
  ],
  "Tax": [
    "News",
    "Tax filing",
    "Income tax",
    "Tax saving",
    "Tax rules",
    "ITR filing",
    "Types of Tax",
    "Direct tax",
    "Indirect tax",
  ],
  "Saving": [
    "News",
    "Importance of saving",
    "Saving tips",
    "Saving measures",
    "Saving benefits",
    "Long term saving",
  ],
};
